name: Daily Work Log Commit

on:
  schedule:
    - cron: '0 20 * * *'  # every day at 20:00 UTC
  workflow_dispatch:

jobs:
  commit-work-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated work log
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add work_log.xlsx
            git commit -m "📒 Daily update to work log on $(date -u +'%Y-%m-%d')"
            git push
          fi
